import { useState } from "react";
import React from "react";
import { useLoader } from "@react-three/fiber";
import * as THREE from "three";

export const useBadgeLoader = () => {
  const [
    bilgewater,
    bilgewater_hover,
    demacia,
    demacia_hover,
    freljord,
    freljord_hover,
    ionia,
    ionia_hover,
    ixtal,
    ixtal_hover,
    noxus,
    noxus_hover,
    piltover_zaun,
    piltover_zaun_hover,
    shadow_isles,
    shadow_isles_hover,
    shurima,
    shurima_hover,
    targon,
    targon_hover,
  ] = useLoader(THREE.TextureLoader, [
    "badge/bilgewater.png",
    "badge/bilgewater-hover.png",
    "badge/demacia.png",
    "badge/demacia-hover.png",
    "badge/freljord.png",
    "badge/freljord-hover.png",
    "badge/ionia.png",
    "badge/ionia-hover.png",
    "badge/ixtal.png",
    "badge/ixtal-hover.png",
    "badge/noxus.png",
    "badge/noxus-hover.png",
    "badge/piltover-zaun.png",
    "badge/piltover-zaun-hover.png",
    "badge/shadow-isles.png",
    "badge/shadow-isles-hover.png",
    "badge/shurima.png",
    "badge/shurima-hover.png",
    "badge/targon.png",
    "badge/targon-hover.png",
  ]);
  return {
    badge: {
      bilgewater,
      bilgewater_hover,
      demacia,
      demacia_hover,
      freljord,
      freljord_hover,
      ionia,
      ionia_hover,
      ixtal,
      ixtal_hover,
      noxus,
      noxus_hover,
      piltover_zaun,
      piltover_zaun_hover,
      shadow_isles,
      shadow_isles_hover,
      shurima,
      shurima_hover,
      targon,
      targon_hover,
    },
  };
};
